/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*stm32f kutuphanesini include etmek icin, daha once hazirlanmis bir projenin kayit edildigi klasorlerin icinde drivers klasorunde CMSIS klasoru kopyalanip
 * register seviyesinde yazilacak olan mevcut projenin kayit edildigi klasorlerinin oldugu dizinde ortaya yapistirilir (drivers klsoru yoktur).
 * Daha sonra solda Project Explorer bolumunde, mevcut proje uzerinde sag tiklanip refresh tiklanir. Klasorler arasinda CMSIS gorulur.
 * Daha sonra solda Project Explorer bolumden, mevcut proje uzerinde sag tiklanip Properties tiklanir. Acilan pencerede solda C/C++ Build in yanindaki ok tiklanir.
 * Altinda acilan menulerden Settings tiklanir. Settings penceresinde MCU/MPU GCC Compiler menusunun altinda Include Paths tiklanir. Include Paths penceresinde yan tarafta
 * Add ikonu tiklanir. Add directory path penceresi acilir. Pencerenin altinda Workspace butonu tiklanir. Folder Selection penceresi acilir. Mevcut proje altinda
 * CMSIS klasoru altinda Device altinda ST altinda STM32F4xx altinda Include klasoru secilip OK tiklanir. Add directory path penceresinde OK tiklanir.
 * Include paths pencersinde yan tarafta Add ikonuna bir kez daha tiklanir. Acilan Add directory path penceresinde alttaki Workspace butonu tiklanir.
 * Acilan Folder Selection pencerinde mevcut proje altinda CMSIS klasoru altinda Include klasoru secilip OK tiklanir. Add directory path penceresinde OK tiklanir.
 * Include paths pencersinde alt tarafta Apply butonu tiklanir. Acilan Settings penceresinde Remember my decision kutucugu isaretlenip Rebuild Index butonu tiklanir.
 * Daha sonra Include paths pencersinde alt tarafta Apply and Close butonu tiklanir. Daha sonra include kodu yazilabilir. #include "stm32f" yazilip ctrl+space basilinca otomatik olarak
 * cubeid nin dogru kutuphaneyi (stm32f030x8.h ve stm32f0xx.h) bulmasi gereklidir. Otomatik olarak bulamadiysa bir hata olmus demektir. Eger mevcut CPU kutuphanesi secilirse (stm32f030x8.h)
 * derleme hatasi alinmaz. Diger kutuphane secilirse (stm32f0xx.h) derleme hatasi alinir. Hatayi duzeltmek icin sol tarafta Project Explorer bolumunde, mevcut proje altinda
 * CMSIS klasorunde x isareti olusur. x isareti takip edilerek en son x isaretinin bulundugu dosya (stm32f0xx.h) tiklanip acilir. Hatanin oldugu satira gidilir. Hatanin oldugu
 * satirin ust kisimlarinda if elif blogunun baslangicindan once #define STM32F030x8 yazilip kayit edildikten sonra build ikonuna tiklanir. Hata olmamasi beklenir.
 */

#include "stm32f030x8.h"

int main(void)
{
    RCC -> AHBENR |=(1<<17);
	GPIOA -> MODER &= ~(3<<(5*2));
	GPIOA -> MODER |= (1<<(5*2));
	GPIOA -> OTYPER &= ~(1<<5);
	GPIOA -> OSPEEDR |= (3<<(5*2));
	GPIOA -> PUPDR &= ~(3<<(5*2));



	/* Loop forever */
	for(;;){
		GPIOA -> ODR |= (1<<5);
		for(int var=0 ;var<1000000;var++);
		GPIOA -> ODR &= ~(1<<5);
		for(int var=0 ;var<1000000;var++);
	}
}
